Web2/Controllers/CredsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web2.Models;

namespace Web2.Controllers
{
    public class CredsController : Controller
    {
        // GET: Creds
        public ActionResult Index()
        {


            return View();
        }

        public ActionResult Reset()
        {
            TableHelper.GetTable().DeleteIfExists();
            KeyVaultAccessor.creds = null;
            return View("reset");
        }
        [HttpPost]
        public ActionResult Index(VaultCredentials creds)
        {
            KeyVaultAccessor.creds = creds;
            ViewBag.Message = "Key Received";
            return PartialView("MessageView");
        }

    }
}

Web2/Views/Creds/Index.cshtml
@model Web2.Models.VaultCredentials

@{
    ViewBag.Title = "Upload your Key Vault Credentials";
}

@using (Ajax.BeginForm( "Index", "Creds",  new AjaxOptions()
{ 
    UpdateTargetId = "Target",
    InsertionMode = InsertionMode.Replace
}
))
{
    <h1>Upload your Credentials</h1>
    <div class="form-horizontal">
                
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.SecretUri, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SecretUri, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SecretUri, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KVClientID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KVClientID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KVClientID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.KVClientKeySecret, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.KVClientKeySecret, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.KVClientKeySecret, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Secure Me" class="btn btn-default" />


            </div>
        </div>

        <div id="Target"></div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <select onchange="setData(this.value);">
                    <option value="0" selected="selected"></option>
                    <option value="1">Greg's Creds</option>
                </select>
            </div>
        </div>

    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")
}

<script language="javascript">

    function UpdateResult() {
        alert('updateresult');
        document.getElementById("result").textContent = "Credentials Submitted"
    }

    function UpdateResult() {
        alert('updatefailure');
        document.getElementById("result").textContent = "Something went wrong"
    }

    function clear()
    {
        alert('clear');
        document.forms.i[0].clear();
    }
        
    function setData( index )
    {
 
        document.getElementById("SecretUri").value = "https://ckeyvault.vault.azure.net:443/secrets/secret";
        document.getElementById("KVClientID").value = "9961e7e9-bf5d-4641-8038-8d6e40308122";
        document.getElementById("KVClientKeySecret").value = "+HEBib6PyYf+UHAje4tfVea0aJrVqBcZdTXuhdCbFfI=";
    }
</script>

Web2/Views/Creds/Reset.cshtml
@{
    ViewBag.Title = "Reset";
}

<h2>KeyVault Reset Complete</h2>